menu:
    Blog: /
    Archive: /archives
    Wiki: https://amoseui.github.com/wiki
    GitHub: https://github.com/amoseui
    Rss: /atom.xml

# favicon: /favicon.png
# logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: blogamoseuicom
# duoshuo: 

# Analytics
google-analytics:
    ga: UA-71786246-2

# Copyright Infomation
startyear: 2016

# Font CDN
#true : use google fonts api, not stable for chinese visitor sometimes, caused by force majeure factor
#false: use useso fonts api instead of google's, great response speed for chinese visitor
googlefonts: false
